### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by David-Woroniuk** [maximenc/pycop#1]
Are there any unit tests associated with this package? It would be great to add some unit tests as part of the CI/CD pipeline.

**Comment by maximenc** [comment]
There isn't, but I'm considering adding it in the future. Thanks for the suggestion

**Comment by David-Woroniuk** [comment]
Great package btw! Happy to contribute on this with a PR if it would help? Maybe mark as an "enhancement" and we can discuss an automated deployment pipeline?

**Comment by maximenc** [comment]
Sure! It would definitely help.
