### ISSUE TITLE
_

### ISSUE THREAD

**Issue by ghost** [maximenc/pycop#12]

**Comment by maximenc** [comment]
Hi there,

After estimating your parameter(s), the CDF can be obtained using the copula function (Sklar’s theorem):

$$ H(x,y) = C \left( F_X(x), F_Y(y) \right) $$

To access the CDF, use:
`cop.get_cdf(u, v, param)`
(u, v in [0, 1])

For the LLF, things get trickier. While the CMLE doesn't account for the marginals, you would need the PDF of the marginals.

The LLF can then be derived from the joint PDF:

$$ h(x,y) = c \left( F_X(x), F_Y(y) \right) f_X(x) f_Y(y) $$

The copula PDF can be accessed with:
`cop.get_pdf(u, v, param)`

I hope this helps.

M.

**Comment by jondo** [comment]
It seems this issue can be closed.
